//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroomService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public long CardId { get; set; }
        public string NameOnCard { get; set; }
        public string Email { get; set; }
        public string CardNumber { get; set; }
        public Nullable<int> CVV { get; set; }
        public Nullable<int> ExpireMonth { get; set; }
        public Nullable<int> ExpireYear { get; set; }
        public Nullable<long> UserId { get; set; }
        public string CardType { get; set; }
    
        public virtual User User { get; set; }
    }
}
