//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroomService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.JobRequestSubSubCategories = new HashSet<JobRequestSubSubCategory>();
            this.JobRequestSubSubCategories1 = new HashSet<JobRequestSubSubCategory>();
            this.SubCategories = new HashSet<SubCategory>();
            this.SubUserRequests = new HashSet<SubUserRequest>();
            this.SubUserRequests1 = new HashSet<SubUserRequest>();
            this.tblCategoryShifts = new HashSet<tblCategoryShift>();
            this.tblCategoryShifts1 = new HashSet<tblCategoryShift>();
            this.UserSubCategories = new HashSet<UserSubCategory>();
            this.ServiceQuotes = new HashSet<ServiceQuote>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Picture { get; set; }
        public Nullable<bool> HasPrice { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Icon { get; set; }
        public Nullable<bool> ForWorkers { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string Name_Russian { get; set; }
        public string Name_Hebrew { get; set; }
        public string Name_French { get; set; }
        public string Description { get; set; }
        public string Description_Russian { get; set; }
        public string Description_Hebrew { get; set; }
        public string Description_French { get; set; }
        public Nullable<bool> SubUserOrder { get; set; }
        public Nullable<bool> SubUserSendRequest { get; set; }
        public Nullable<int> NoOfShifts { get; set; }
        public string Time { get; set; }
        public Nullable<bool> ForAirbnb { get; set; }
        public Nullable<bool> ForNormalProprrty { get; set; }
        public Nullable<bool> ForSubUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobRequestSubSubCategory> JobRequestSubSubCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobRequestSubSubCategory> JobRequestSubSubCategories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubCategory> SubCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubUserRequest> SubUserRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubUserRequest> SubUserRequests1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCategoryShift> tblCategoryShifts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCategoryShift> tblCategoryShifts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSubCategory> UserSubCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceQuote> ServiceQuotes { get; set; }
    }
}
