//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroomService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckRequest
    {
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public string PropertyName { get; set; }
        public string PropertyAddress { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    }
}
