//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroomService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobInventory
    {
        public long JobInventoryId { get; set; }
        public Nullable<long> InventoryId { get; set; }
        public Nullable<long> JobRequestId { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<long> PropertyId { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual Inventory Inventory1 { get; set; }
        public virtual JobRequestPropertyService JobRequestPropertyService { get; set; }
        public virtual JobRequestPropertyService JobRequestPropertyService1 { get; set; }
    }
}
