//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroomService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobRequestQuoteType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobRequestQuoteType()
        {
            this.JobRequestQuoteDetails = new HashSet<JobRequestQuoteDetail>();
            this.JobRequestQuoteDetails1 = new HashSet<JobRequestQuoteDetail>();
        }
    
        public long QuoteTypeId { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<long> JobRequestId { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string MeetingTime { get; set; }
    
        public virtual JobRequest JobRequest { get; set; }
        public virtual JobRequest JobRequest1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobRequestQuoteDetail> JobRequestQuoteDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobRequestQuoteDetail> JobRequestQuoteDetails1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
