//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroomService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobRequestQuoteDetail
    {
        public long QuoteDetailsId { get; set; }
        public Nullable<long> QuoteTypeId { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<bool> IsImage { get; set; }
        public string VideoUrl { get; set; }
        public Nullable<bool> IsVideo { get; set; }
        public string Description { get; set; }
    
        public virtual JobRequestQuoteType JobRequestQuoteType { get; set; }
        public virtual JobRequestQuoteType JobRequestQuoteType1 { get; set; }
    }
}
