//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroomService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobRequestPropertyService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobRequestPropertyService()
        {
            this.JobInventories = new HashSet<JobInventory>();
            this.JobInventories1 = new HashSet<JobInventory>();
            this.JobRequestSubSubCategories = new HashSet<JobRequestSubSubCategory>();
            this.JobRequestSubSubCategories1 = new HashSet<JobRequestSubSubCategory>();
            this.OccupiedProviders = new HashSet<OccupiedProvider>();
            this.OccupiedProviders1 = new HashSet<OccupiedProvider>();
            this.UserJobReviews = new HashSet<UserJobReview>();
            this.UserJobReviews1 = new HashSet<UserJobReview>();
        }
    
        public long JobRequestPropId { get; set; }
        public Nullable<long> JobRequestId { get; set; }
        public Nullable<long> PropertyId { get; set; }
        public Nullable<long> ServiceId { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<int> TimeToDo { get; set; }
        public Nullable<bool> type { get; set; }
        public Nullable<long> AssignedWorker { get; set; }
        public Nullable<int> JobStatus { get; set; }
        public Nullable<int> NewTimeToDo { get; set; }
        public string Comment { get; set; }
        public Nullable<long> CommentAddedBy { get; set; }
        public Nullable<System.DateTime> TimerStartDate { get; set; }
        public Nullable<System.DateTime> TimerEndDate { get; set; }
        public Nullable<bool> IsVisitor { get; set; }
        public string Gender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobInventory> JobInventories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobInventory> JobInventories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobRequestSubSubCategory> JobRequestSubSubCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobRequestSubSubCategory> JobRequestSubSubCategories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OccupiedProvider> OccupiedProviders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OccupiedProvider> OccupiedProviders1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserJobReview> UserJobReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserJobReview> UserJobReviews1 { get; set; }
    }
}
