//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroomService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaundryRequest
    {
        public long LaundryRequestId { get; set; }
        public int LaundryItems { get; set; }
        public int IroningItems { get; set; }
        public int DryingItems { get; set; }
        public System.DateTime PickupDate { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public decimal Price { get; set; }
        public int LaundryStatus { get; set; }
        public long PickupGuyId { get; set; }
        public long PropertyId { get; set; }
        public Nullable<long> JobRequestId { get; set; }
        public long UserId { get; set; }
        public Nullable<long> ReturnGuyId { get; set; }
        public Nullable<long> LaundryId { get; set; }
    }
}
