//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroomService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthInvoice
    {
        public int Id { get; set; }
        public string UserID { get; set; }
        public string Description { get; set; }
        public string Price { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
