//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroomService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public long Id { get; set; }
        public Nullable<long> JobRequestId { get; set; }
        public string Text { get; set; }
        public Nullable<long> FromUserId { get; set; }
        public Nullable<long> ToUserId { get; set; }
        public Nullable<int> NotificationStatus { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string QuotePrice { get; set; }
        public string PropertyName { get; set; }
        public string PropertyAddress { get; set; }
        public string ServiceName { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
    }
}
