//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroomService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OccupiedProvider
    {
        public long OccupiedProviderId { get; set; }
        public Nullable<long> ProviderId { get; set; }
        public string FromTime { get; set; }
        public string ToTime { get; set; }
        public Nullable<long> JobPropertyServiceId { get; set; }
        public Nullable<System.DateTime> JobDateTime { get; set; }
        public Nullable<bool> IsDeliveryGuy { get; set; }
        public Nullable<bool> IsDeliveryDone { get; set; }
    
        public virtual JobRequestPropertyService JobRequestPropertyService { get; set; }
        public virtual JobRequestPropertyService JobRequestPropertyService1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
