//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroomService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyReport
    {
        public long Id { get; set; }
        public long PropertyId { get; set; }
        public string Reason { get; set; }
        public string Comment { get; set; }
        public bool Resolved { get; set; }
    
        public virtual Property Property { get; set; }
    }
}
