//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroomService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Property()
        {
            this.PropertyJobRequests = new HashSet<PropertyJobRequest>();
            this.PropertyJobRequests1 = new HashSet<PropertyJobRequest>();
            this.PropertyReports = new HashSet<PropertyReport>();
            this.tblGrantProperties = new HashSet<tblGrantProperty>();
            this.tblGrantProperties1 = new HashSet<tblGrantProperty>();
            this.ServiceQuotes = new HashSet<ServiceQuote>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public Nullable<bool> ShortTermApartment { get; set; }
        public Nullable<int> FloorNumber { get; set; }
        public Nullable<int> ApartmentNumber { get; set; }
        public string BuildingCode { get; set; }
        public string AccessToProperty { get; set; }
        public Nullable<int> NoOfBathrooms { get; set; }
        public Nullable<int> NoOfQueenBeds { get; set; }
        public Nullable<int> NoOfDoubleBeds { get; set; }
        public Nullable<int> NoOfSingleBeds { get; set; }
        public Nullable<int> NoOfSingleSofaBeds { get; set; }
        public Nullable<int> NoOfDoubleSofaBeds { get; set; }
        public Nullable<bool> Doorman { get; set; }
        public Nullable<bool> Parking { get; set; }
        public Nullable<bool> Balcony { get; set; }
        public Nullable<bool> Dishwasher { get; set; }
        public Nullable<bool> Pool { get; set; }
        public Nullable<bool> Garden { get; set; }
        public Nullable<bool> Elevator { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<int> NoOfToilets { get; set; }
        public Nullable<int> NoOfBedRooms { get; set; }
        public string Size { get; set; }
        public Nullable<long> CountryId { get; set; }
        public Nullable<long> CityId { get; set; }
        public string WifiLogin { get; set; }
        public Nullable<bool> CoffeeMachine { get; set; }
        public Nullable<bool> IsSingleBed { get; set; }
        public Nullable<bool> IsKingBed { get; set; }
        public Nullable<bool> IsSofaBed { get; set; }
        public Nullable<bool> AccesstoCode { get; set; }
        public Nullable<long> SubUserId { get; set; }
        public string LocationOfKey { get; set; }
        public Nullable<decimal> RoomPrice { get; set; }
        public Nullable<int> NoOfkingBeds { get; set; }
        public Nullable<decimal> Price2Star { get; set; }
        public Nullable<decimal> Price3Star { get; set; }
        public Nullable<decimal> Price4Star { get; set; }
        public Nullable<decimal> Price5Star { get; set; }
        public Nullable<decimal> DeluxPrice { get; set; }
        public Nullable<long> AccomodationId { get; set; }
        public string AccomodationName { get; set; }
        public string Status { get; set; }
        public bool Blocked { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyJobRequest> PropertyJobRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyJobRequest> PropertyJobRequests1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyReport> PropertyReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGrantProperty> tblGrantProperties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGrantProperty> tblGrantProperties1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceQuote> ServiceQuotes { get; set; }
        public virtual User User { get; set; }
    }
}
