//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroomService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyVisit
    {
        public long Id { get; set; }
        public Nullable<long> PropertyId { get; set; }
        public Nullable<bool> PropertyVisit1 { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<int> UserType { get; set; }
        public string PropertyName { get; set; }
        public string PropertyAddress { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
