//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroomService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RejectJobRequest
    {
        public long Id { get; set; }
        public Nullable<long> JobRequestId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> UserId { get; set; }
        public string Reason { get; set; }
        public string Text { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Notify { get; set; }
        public string PropertyName { get; set; }
    
        public virtual JobRequest JobRequest { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
