//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroomService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceAutoPrice
    {
        public long ServiceId { get; set; }
        public string Size { get; set; }
        public int Price { get; set; }
        public int ServiceProviderPrice { get; set; }
        public string Time { get; set; }
    }
}
