//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroomService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceQuote
    {
        public long Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<long> PropertyId { get; set; }
        public Nullable<long> ServiceId { get; set; }
        public Nullable<long> SubCategoryId { get; set; }
        public Nullable<long> SubSubCategoryId { get; set; }
        public Nullable<decimal> QuotePrice { get; set; }
        public Nullable<bool> IsQuoteApproved { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<long> QuotedBy { get; set; }
        public Nullable<decimal> SpPrice { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Property Property { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual User User { get; set; }
    }
}
