//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroomService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicePriceChangeRequest
    {
        public long Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> SubCatId { get; set; }
        public Nullable<long> SubSubCatId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> RequestStatus { get; set; }
        public Nullable<decimal> OldPrice { get; set; }
        public Nullable<decimal> NewPrice { get; set; }
    }
}
