//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroomService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAddServiceRequest
    {
        public int Id { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> SubCatId { get; set; }
        public Nullable<int> SubSubCatId { get; set; }
        public Nullable<long> PropertId { get; set; }
        public Nullable<long> UserId { get; set; }
        public string JobStartDateTime { get; set; }
        public Nullable<long> AssignWorker { get; set; }
        public string Message { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public Nullable<decimal> ServicePrice { get; set; }
    }
}
