//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroomService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCategoryShift
    {
        public long ShiftID { get; set; }
        public Nullable<long> CategoryId { get; set; }
        public Nullable<int> ShiftNumber { get; set; }
        public Nullable<int> SelectedTime { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Category Category1 { get; set; }
        public virtual tblCategoryShift tblCategoryShifts1 { get; set; }
        public virtual tblCategoryShift tblCategoryShift1 { get; set; }
    }
}
