//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroomService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEditJobRequest
    {
        public int Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> JobRequestId { get; set; }
        public Nullable<long> OldPropertyId { get; set; }
        public Nullable<long> NewPropertyId { get; set; }
        public Nullable<System.DateTime> OldServiceDateTime { get; set; }
        public Nullable<System.DateTime> NewServiceDateTime { get; set; }
        public Nullable<long> AssignWorker { get; set; }
        public Nullable<bool> IsApproved { get; set; }
    }
}
