//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroomService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGrantAccess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblGrantAccess()
        {
            this.tblGrantProperties = new HashSet<tblGrantProperty>();
            this.tblGrantProperties1 = new HashSet<tblGrantProperty>();
        }
    
        public long GrantAccessId { get; set; }
        public string Email { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> OrderServicesAccess { get; set; }
        public Nullable<bool> AddEditPropertiesAccess { get; set; }
        public Nullable<bool> BillingPriceAccess { get; set; }
        public Nullable<bool> AddChangeCardAccess { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> ForAllProperties { get; set; }
        public Nullable<bool> IsAccountAccepted { get; set; }
        public Nullable<long> UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGrantProperty> tblGrantProperties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGrantProperty> tblGrantProperties1 { get; set; }
    }
}
