//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroomService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMessage
    {
        public long MsgId { get; set; }
        public string Message { get; set; }
        public Nullable<long> MsgTypeId { get; set; }
    
        public virtual tblMessageType tblMessageType { get; set; }
        public virtual tblMessageType tblMessageType1 { get; set; }
    }
}
