//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroomService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProviderAvailableTime
    {
        public long Id { get; set; }
        public Nullable<long> provider_id { get; set; }
        public string from_time { get; set; }
        public string to_time { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> day_of_week { get; set; }
        public Nullable<bool> isOptionalOff { get; set; }
        public Nullable<bool> isCausallOff { get; set; }
        public Nullable<int> week_of_year { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public Nullable<System.DateTime> vDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
