//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroomService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSavedChecklist
    {
        public long Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public string ChecklistName { get; set; }
        public Nullable<long> PropertyId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> SubServiceId { get; set; }
        public Nullable<int> SubSubServiceId { get; set; }
    }
}
