//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroomService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSubCategory
    {
        public long Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> SubCategoryId { get; set; }
        public Nullable<long> SubSubCategoryId { get; set; }
        public Nullable<long> CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual SubSubCategory SubSubCategory { get; set; }
        public virtual User User { get; set; }
    }
}
