//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroomService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserChat
    {
        public long Id { get; set; }
        public Nullable<long> FromUserId { get; set; }
        public Nullable<long> ToUserId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string LastMessage { get; set; }
        public string LastMsgDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
    }
}
