//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroomService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserChannelManagerSetting
    {
        public long UserChannelManagerSettingsId { get; set; }
        public long UserChannelManagerId { get; set; }
        public bool CheckInCleaning { get; set; }
        public bool WindowsCleaning { get; set; }
        public bool LundryPickup { get; set; }
        public bool LinenRentals { get; set; }
        public bool Amenties { get; set; }
        public Nullable<long> FastOrderId { get; set; }
    }
}
