//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroomService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserChannelManager
    {
        public long UserChannelManagerId { get; set; }
        public long ChannelManagerId { get; set; }
        public long UserId { get; set; }
        public string ApiKey { get; set; }
        public bool Active { get; set; }
        public string ChannelManagerUsername { get; set; }
        public string ChannelManagerPassword { get; set; }
    }
}
